t0: 0
tf: 300

S0: 1000000
L0: 0
I0: 1
A0: 0

beta: 5.27e-07
sigma: 0
kappa: 0.526
alpha: 0.244
tau: 0
p: 0.667
eta: 0.244
epsilon: 0
q: 0.5
delta: 1

P: 1
Q: 1
R: 0
W: 0

MaxIter: 1000
update_weight: 0.1
tolerance: 1.0e-09

hydra:
  job:
    chdir: true

defaults:
  - override hydra/launcher: joblib
